Controllers/CoffeeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CoffeaAndTeaLeaves.Models;

namespace CoffeaAndTeaLeaves.Controllers;

public class CoffeeController : Controller
{
// storing Get UserID in session into variable uid
    private int? uid
    {
        get{
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    // variable to check if logged in
    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }

    private CandTContext db;
    public CoffeeController(CandTContext context)
    {
        db = context;
    }


    // ================
    // View Coffee Dashboard
    // ================
    [HttpGet("/candt/coffee")]
    public IActionResult All()
    {   
        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));

        ParentViewModel AllModels = new ParentViewModel
        {   
            AllCoffees = db.Coffees
                .OrderByDescending(c => c.CreatedAt)
                .ToList(),
            User = user
        };

        return View("AllCoffee", AllModels);
    }


    // ================
    // Coffee Admin View
    // ================
    [HttpGet("/candt/coffee/admin")]
    public IActionResult AdminAllCoffee()
    {
        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));
        
        if(user.Admin){
            Console.WriteLine((int)uid);
        }


        ParentViewModel AllModels = new ParentViewModel
        {   
            AllCoffees = db.Coffees
                .OrderByDescending(c => c.UpdatedAt)
                .ToList(),
            User = user
        };

        return View("AdmincoffeeView", AllModels);
    }



    // ================
    // Create A Coffee
    // ================
    [SessionCheck]
    [HttpPost("/candt/coffee/new")]
    public IActionResult NewCoffee(Coffee newCoffee)
    {   
        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));
        
        if(user.Admin){
            Console.WriteLine((int)uid);
        }


        ParentViewModel AllModels = new ParentViewModel
        {   
            AllCoffees = db.Coffees
                .OrderByDescending(c => c.CreatedAt)
                .ToList(),
            User = user
        };

        if(!ModelState.IsValid)
        {
            return AdminAllCoffee();
        }

        db.Coffees.Add(newCoffee);
        db.SaveChanges();
        
        return RedirectToAction("AdminAllCoffee", AllModels);
    }

    // ================
    // View A Coffee
    // ================
    [HttpGet("/candt/coffee/{oneCoffeeId}/view")]
    public IActionResult GetOne(int oneCoffeeId)
    {
        // ? makes return able to be nullable
        Coffee? oneCoffee = db.Coffees
            // .Include(p =>p.DishLikes)
            //     .ThenInclude(l => l.User)
            .FirstOrDefault(coffee => coffee.CoffeeId == oneCoffeeId);

        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));

        ParentViewModel AllModels = new ParentViewModel
        {   
            AllCoffees = db.Coffees
                .OrderByDescending(c => c.CreatedAt)
                .ToList(),
            User = user,
            Coffee = oneCoffee
        };


        // if oneCoffee null, redirect
        if(oneCoffee == null)
        {
            return RedirectToAction("All", AllModels);
        }

        return View("OneCoffee", AllModels);
    }



    // ================
    // Edit A Coffee - Render
    // ================
    [HttpGet("/candt/coffee/{oneCoffeeId}/edit")]
    public IActionResult EditCoffee(int oneCoffeeId)
    {
        // ? makes return able to be nullable
        Coffee? oneCoffee = db.Coffees
            // .Include(p =>p.DishLikes)
            //     .ThenInclude(l => l.User)
            .FirstOrDefault(coffee => coffee.CoffeeId == oneCoffeeId);

        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));

        ParentViewModel AllModels = new ParentViewModel
        {   
            AllCoffees = db.Coffees
                .OrderByDescending(c => c.CreatedAt)
                .ToList(),
            User = user
        };


        // if oneCoffee null, redirect
        if(oneCoffee == null)
        {
            return RedirectToAction("All", AllModels);
        }

        return View("EditCoffee", oneCoffee);
    }


    // ================
    // Edit A Coffee - Post
    // ================
    [HttpPost("/candt/coffee/{editCoffeeId}/update")]
    public IActionResult UpdateCoffee(Coffee editedCoffee, int editCoffeeId)
    {   
        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));
        
        if(user.Admin){
            Console.WriteLine((int)uid);
        }

        if(!ModelState.IsValid)
        {
            return AdminAllCoffee();
        }
        
            Coffee? dbCoffee = db.Coffees.FirstOrDefault(coffee => coffee.CoffeeId == editCoffeeId);
            if(dbCoffee == null)
            {   
                Console.WriteLine("========");
                return RedirectToAction("AdminAllCoffee");
            }

            dbCoffee.Name = editedCoffee.Name;
            dbCoffee.Price = editedCoffee.Price;
            dbCoffee.Region = editedCoffee.Region;
            dbCoffee.Roast = editedCoffee.Roast;
            dbCoffee.ImgUrl = editedCoffee.ImgUrl;
            dbCoffee.Quantity = editedCoffee.Quantity;
            
            
            // if it exists && validated, update info
            dbCoffee.UpdatedAt = DateTime.Now;

            db.Coffees.Update(dbCoffee);
            db.SaveChanges();
            Console.WriteLine("====***********************=====");
            return RedirectToAction("GetOne", new {oneCoffeeId= editCoffeeId});


    }


    // ============================================
    // Delete Coffee Route
    // ============================================
    [HttpPost("/candt/{deletedCoffeeId}/coffee")]
    public IActionResult DeleteCoffee(int deletedCoffeeId)
    {
        
        Coffee? coffee = db.Coffees.FirstOrDefault(c => c.CoffeeId == deletedCoffeeId);

        if(coffee != null)
        {
            db.Coffees.Remove(coffee);
            db.SaveChanges();
        }
        return RedirectToAction("All");
    }
}

Controllers/PinController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using CoffeaAndTeaLeaves.Models;

namespace CoffeaAndTeaLeaves.Controllers;

public class PinController : Controller
{
// storing Get UserID in session into variable uid
    private int? uid
    {
        get{
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    // variable to check if logged in
    private bool loggedIn
    {
        get
        {
            return uid != null;
        }
    }


    // dependency injection => allowing us to manipulate database
    private CandTContext db;
    public PinController(CandTContext context)
    {
        db = context;
    }


    // ================
    // Dashboard
    // ================
    [SessionCheck]
    [HttpGet("/candt/dashboard")]
    public IActionResult Dashboard(string searchString)
    {
        User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));
        

        
        ParentViewModel AllModels = new ParentViewModel
        {
            AllPins = db.Pins
                .OrderByDescending(p => p.CreatedAt)
                .Include(p => p.PinPoster)
                .ToList(),
            AllLikes = db.Likes.ToList(),
            AllUsers = db.Users.ToList(),
            User = user,
        };
        return View("Dashboard", AllModels);
    }

    

    // ================
    // Create A Pin
    // ================
    [SessionCheck]
    [HttpPost("/candt/pins/new")]
    public IActionResult NewPin(Pin newPin)
    {
        if(!ModelState.IsValid)
        {   
            User? user = db.Users
            .FirstOrDefault(u => u.UserId == HttpContext.Session.GetInt32("UUID"));
        

            
            ParentViewModel AllModels = new ParentViewModel
            {
                AllPins = db.Pins
                    .OrderByDescending(p => p.CreatedAt)
                    .Include(p => p.PinPoster)
                    .ToList(),
                AllLikes = db.Likes.ToList(),
                AllUsers = db.Users.ToList(),
                User = user,
            };
            return View("Dashboard", AllModels);
        }

        newPin.UserId = (int)uid;

        db.Pins.Add(newPin);
        db.SaveChanges();
        
        return RedirectToAction("Dashboard");
    }



    // ================
    // Delete A Pin
    // ================
    [HttpPost("/candt/pins/{deletePinId}/delete")]
    public IActionResult DeletePin(int deletePinId)
    {
        Pin? pin = db.Pins.FirstOrDefault(p => p.PinId == deletePinId);
        if(pin != null)
        {
            db.Pins.Remove(pin);
            db.SaveChanges();
            Console.WriteLine("Removed pin from database");
        }

        return RedirectToAction("Dashboard");
    }
    

}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CoffeaAndTeaLeaves</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CoffeaAndTeaLeaves.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="d-flex navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <img src="~/images/companyicon.png" alt="company logo">
                @{
                    int? userId = Context.Session.GetInt32("UUID");
                }

                @if(userId > 0)
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Pin" asp-action="Dashboard">Coffea And Tea Leaves</a>
                }
                else 
                {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Coffea And Tea Leaves</a>
                }
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if(userId > 0)
                        {
                            <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pin" asp-action="Dashboard">Dashboard</a>
                            </li>
                        }
                        else{
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coffee" asp-action="All">Coffee</a>
                        </li>
                        @if(Context.Session.GetInt32("UUID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="AllContacts">Contact Info</a>
                            </li>
                            <li class="nav-item">
                                <form 
                                    asp-controller="User" 
                                    asp-action="Logout"
                                    method="POST">
                                    <button class="nav-link text-dark border-0 bg-transparent">
                                        Logout
                                    </button>
                                </form>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Coffea And Tea Leaves - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>